[tools]
rust = "nightly-2026-08-16"

[tasks.fmt]
run = "cargo fmt --all -- --check"

[tasks.fmt-fix]
run = "cargo fmt --all"

[tasks.check]
run = "cargo check --all-targets"

[tasks.test]
run = "cargo test --all-targets"

[tasks.clippy]
run = "cargo clippy --all-targets -- -D warnings"

[tasks.doc]
run = "cargo doc --no-deps"

[tasks.doc-test]
run = "cargo test --doc"

[tasks.package-list]
run = "cargo package --list --allow-dirty"

[tasks.publish-dry-run]
run = "cargo publish --dry-run --allow-dirty"

[tasks.publish]
run = "cargo publish"
